name: Snyk
on: push
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setuo@master
      - name: Run Snyk to check for vulnerabilities
        run: snyk code test --sarif > snyk_sarif
        env:
          SNYK_TOKEN: ab5f1850-30fc-4112-a60e-2c169e0c1129
      - name: Upload results to Github Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk_sarif
