name: Snyk
on: 
  workflow_dispatch:
  push:
    branches: [ main,realese ]
  pull_request:
    branches: [ main,realese ]  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run driftctl
        uses: snyk/driftctl-action@v1
        with:
          version: 0.38.2
